name: Despliegue de Blazor PWA

on:
  push:
    branches: [ main, master ]  # Cubrimos ambas posibilidades
  workflow_dispatch:            # <--- ESTO permite lanzar la acción manualmente

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publicar aplicación
        run: dotnet publish -c Release -o release

      # Paso crítico: Cambiar el base-href para GitHub Pages
      - name: Cambiar base-href
        run: sed -i 's/<base href="\/" \/>/<base href="\/MiHolaMundoPWA\/" \/>/g' release/wwwroot/index.html

      # Evitar que GitHub intente procesar con Jekyll
      - name: Añadir .nojekyll
        run: touch release/wwwroot/.nojekyll

      - name: Desplegar en GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages
