name: Despliegue de Blazor PWA

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

# ESTO SOLUCIONA EL ERROR 128
permissions:
  contents: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publicar aplicación
        # AQUÍ CAMBIAMOS EL COMANDO PARA APUNTAR AL PROYECTO
        # Reemplaza 'NombreDeTuCarpeta' por el nombre de la carpeta de tu código
        run: dotnet publish MiHolaMundoPWA/*.csproj -c Release -o release

      - name: Cambiar base-href
        # Reemplaza 'NombreDeTuRepo' por el nombre de tu repositorio en GitHub
        run: sed -i 's/<base href="\/" \/>/<base href="\/MiHolaMundoPWA\/" \/>/g' release/wwwroot/index.html

      - name: Añadir .nojekyll
        run: touch release/wwwroot/.nojekyll

      - name: Desplegar en GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages